In [ ]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from data.real_example.preprocessing import load_data_binary
# Evaluate imputation methods on unanimous expert labels
from utils.real_example.evaluation import evaluate_imputers, visualize_evaluation_results

X, y_groundtruth, y_experts = load_data_binary(data_file='data\\real_example\\data.csv', gt_file='data\\real_example\\ground_truth.xlsx')

# 1. Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

[224.81532683 112.78568802  79.43979549  63.06113254  53.40093713
  43.4424607   37.26446665  27.70469858  25.62266103  23.61337119]
Created directory: tests\10_d
Generating and saving plots...
Saved: tests\10_d\Accuracy_bar_plot.png
Saved: tests\10_d\Recall_Class_1_bar_plot.png
Saved: tests\10_d\Precision_Class_1_bar_plot.png
Saved: tests\10_d\F1_Class_1_bar_plot.png
Saved: tests\10_d\Pi_Diff_Class_1_bar_plot.png
Generating and saving plots...
Saved: tests\10_d\Accuracy_bar_plot.png
Saved: tests\10_d\Recall_Class_1_bar_plot.png
Saved: tests\10_d\Precision_Class_1_bar_plot.png
Saved: tests\10_d\F1_Class_1_bar_plot.png
Saved: tests\10_d\Pi_Diff_Class_1_bar_plot.png

All plots saved to 'tests\10_d/' directory.

,Accuracy,Recall_Class_0,Recall_Class_1,Precision_Class_1,F1_Class_1,TP,FP,TN,FN,Pi_Estimated,Pi_Empirical,Pi_Diff_Class_1
Imputer,,,,,,,,,,,,
Mode Imputer,0.763158,0.285714,0.945455,0.776119,0.852459,52,15,6,3,0.795455,0.881579,0.071770
KNN Imputer (k=5),0.881579,0.761905,0.927273,0.910714,0.918919,51,5,16,4,0.768421,0.736842,0.044737
Random Forest Imputer,0.815789,0.523810,0.927273,0.836066,0.879310,51,10,11,4,0.751053,0.802632,0.027368
EM-GMM Imputer,0.763158,0.285714,0.945455,0.776119,0.852459,52,15,6,3,0.881579,0.881579,0.157895

In [ ]:
# 2. Apply PCA (Retaining )
pca = PCA(n_components=10)
X_pca = pca.fit_transform(X_scaled)
print(f"Explained variance= {pca.explained_variance_ratio_.sum()} \n")
# Run a small experiment (reduce `n_repeats` for quicker runs)
results_df = evaluate_imputers(X_pca, y_experts, y_groundtruth)
agg = visualize_evaluation_results(results_df, save_dir='tests\\10_d')

# # Display a quick summary
results_df

Explained variance= 0.7341834791542607
Generating and saving plots...
Saved: tests\10_d\Accuracy_bar_plot.png
Saved: tests\10_d\Recall_Class_1_bar_plot.png
Saved: tests\10_d\Precision_Class_1_bar_plot.png
Saved: tests\10_d\F1_Class_1_bar_plot.png
Saved: tests\10_d\Pi_Diff_Class_1_bar_plot.png
Generating and saving plots...
Saved: tests\10_d\Accuracy_bar_plot.png
Saved: tests\10_d\Recall_Class_1_bar_plot.png
Saved: tests\10_d\Precision_Class_1_bar_plot.png
Saved: tests\10_d\F1_Class_1_bar_plot.png
Saved: tests\10_d\Pi_Diff_Class_1_bar_plot.png

All plots saved to 'tests\10_d/' directory.

,Accuracy,Recall_Class_0,Recall_Class_1,Precision_Class_1,F1_Class_1,TP,FP,TN,FN,Pi_Estimated,Pi_Empirical,Pi_Diff_Class_1
Imputer,,,,,,,,,,,,
Mode Imputer,0.763158,0.285714,0.945455,0.776119,0.852459,52,15,6,3,0.795455,0.881579,0.071770
KNN Imputer (k=5),0.881579,0.761905,0.927273,0.910714,0.918919,51,5,16,4,0.768421,0.736842,0.044737
Random Forest Imputer,0.815789,0.523810,0.927273,0.836066,0.879310,51,10,11,4,0.751053,0.802632,0.027368
EM-GMM Imputer,0.763158,0.285714,0.945455,0.776119,0.852459,52,15,6,3,0.881579,0.881579,0.157895

In [15]:
# 2. Apply PCA (Retaining )
pca = PCA(n_components=3)
X_pca = pca.fit_transform(X_scaled)
print(f"Explained variance= {pca.explained_variance_ratio_.sum()} \n")
# Run a small experiment (reduce `n_repeats` for quicker runs)
results_df = evaluate_imputers(X_pca, y_experts, y_groundtruth)
agg = visualize_evaluation_results(results_df, save_dir='tests\\3_d')

# # Display a quick summary
results_df

Explained variance= 0.4430069228041906

Generating and saving plots...
Saved: tests\3_d\Accuracy_bar_plot.png
Saved: tests\3_d\Recall_Class_1_bar_plot.png
Saved: tests\3_d\Precision_Class_1_bar_plot.png
Saved: tests\3_d\F1_Class_1_bar_plot.png
Saved: tests\3_d\Pi_Diff_Class_1_bar_plot.png
Generating and saving plots...
Saved: tests\3_d\Accuracy_bar_plot.png
Saved: tests\3_d\Recall_Class_1_bar_plot.png
Saved: tests\3_d\Precision_Class_1_bar_plot.png
Saved: tests\3_d\F1_Class_1_bar_plot.png
Saved: tests\3_d\Pi_Diff_Class_1_bar_plot.png

All plots saved to 'tests\3_d/' directory.

,Accuracy,Recall_Class_0,Recall_Class_1,Precision_Class_1,F1_Class_1,TP,FP,TN,FN,Pi_Estimated,Pi_Empirical,Pi_Diff_Class_1
Imputer,,,,,,,,,,,,
Mode Imputer,0.763158,0.285714,0.945455,0.776119,0.852459,52,15,6,3,0.795455,0.881579,0.071770
KNN Imputer (k=5),0.802632,0.476190,0.927273,0.822581,0.871795,51,11,10,4,0.797368,0.815789,0.073684
Random Forest Imputer,0.736842,0.380952,0.872727,0.786885,0.827586,48,13,8,7,0.763289,0.802632,0.039605
EM-GMM Imputer,0.750000,0.619048,0.800000,0.846154,0.822430,44,8,13,11,0.706457,0.684211,0.017227